export const apis = {
  get_auth: "/v1/get-auth",
  signup: "/v1/auth/sign-up",
  sign_in: "/v1/auth/sign-in",
  logout: "/v1/auth/logout",
  auth: "/v1/auth",
  ai_personas: "/v1/ai-personas/",
  google: "/v1/auth/google",
  interaction_modes_by_name: "/v1/interaction-modes/by-name",
  sessions: "/v1/sessions/",
  chat_chat: "/v1/ai-persona-chat/chat",
  geography: "/v1/geography",
  industries: "/v1/industries/",
  ai_roles: "/v1/ai-roles/",
  manufacturing_models: "/v1/manufacturing-models/",
  plant_size_impacts: "/v1/plant-size-impacts/",
  product_categories: "/v1/produced-product-categories/",
  interaction_mode_ai_roles: "/v1/interaction-mode-ai-roles/",
  interaction_mode_manufacturing_models:
    "/v1/interaction-mode-manufacturing-models/",
  interaction_mode_plant_size_impacts:
    "/v1/interaction-mode-plant-size-impacts/",
  performance_reports: "/v1/performance-reports/",
  coaching: "/v1/ai-coaching/feedback/",
  documents_upload: "/v1/documents/upload",
  feedback: "/v1/feedback/",
  auth_me: "/v1/auth/me",
  subscription: "/v1/subscriptions/",
  // Payment APIs
  create_payment_intent: "/v1/payments/create-payment-intent",
  get_payment_status: "/v1/payments/payment-intent",
  get_user_payments: "/v1/payments/by-user",
  get_user_subscription: "/v1/user-subscriptions/my-subscription",
  // User subscription APIs
  user_subscriptions: "/v1/user-subscriptions/",
  // Password reset APIs
  password_reset_request: "/v1/auth/password-reset/request",
  verify_otp: "/v1/auth/verify-otp",
  password_reset_confirm: "/v1/auth/password-reset/confirm",
  password_reset_final: "/v1/auth/password-reset/final",
};
